"""
MCP Server Generator: Genera servidores MCP completos desde descripciones.

Soporta generación en Python (FastMCP) y TypeScript (@modelcontextprotocol/sdk).
Gestiona ciclo de vida: crear, listar, iniciar, detener, eliminar.
"""

import json
import os
import shutil
import signal
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional

from app.core.logging import log


class MCPGenerator:
    """
    Generador de servidores MCP completos.

    Crea servidores listos para ejecutar a partir de un nombre,
    descripción y lista de herramientas.
    """

    def __init__(self):
        self.output_dir = Path("data/mcp-servers")
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self._running_processes: Dict[str, subprocess.Popen] = {}
        log.info(f"MCPGenerator initialized, output_dir={self.output_dir}")

    # ==================== GENERATION ====================

    def generate(
        self,
        name: str,
        description: str,
        tools: List[dict],
        language: str = "python",
    ) -> dict:
        """
        Genera un servidor MCP completo.

        Args:
            name: Nombre del servidor (usado como directorio y ID)
            description: Descripción del servidor
            tools: Lista de herramientas, cada una con {name, description, parameters}
            language: "python" o "typescript"

        Returns:
            dict con server_id, path, language, tools_count
        """
        server_dir = self.output_dir / name
        server_dir.mkdir(parents=True, exist_ok=True)

        if language == "python":
            self._generate_python(server_dir, name, description, tools)
        elif language == "typescript":
            self._generate_typescript(server_dir, name, description, tools)
        else:
            raise ValueError(f"Unsupported language: {language}. Use 'python' or 'typescript'.")

        # Write metadata
        metadata = {
            "server_id": name,
            "description": description,
            "language": language,
            "tools_count": len(tools),
            "tools": tools,
            "created_at": datetime.now(timezone.utc).isoformat(),
        }
        with open(server_dir / "metadata.json", "w") as f:
            json.dump(metadata, f, indent=2)

        log.info(f"MCP server generated: {name} ({language}, {len(tools)} tools)")

        return {
            "server_id": name,
            "path": str(server_dir),
            "language": language,
            "tools_count": len(tools),
        }

    def _generate_python(
        self,
        server_dir: Path,
        name: str,
        description: str,
        tools: List[dict],
    ) -> None:
        """Genera servidor MCP en Python con FastMCP."""

        # --- server.py ---
        tool_functions = []
        for tool in tools:
            tool_name = tool.get("name", "unnamed_tool")
            tool_desc = tool.get("description", "No description")
            params = tool.get("parameters", [])

            # Build parameter list
            param_strs = []
            for p in params:
                p_name = p.get("name", "arg")
                p_type = p.get("type", "str")
                p_default = p.get("default")
                type_map = {
                    "string": "str",
                    "str": "str",
                    "integer": "int",
                    "int": "int",
                    "number": "float",
                    "float": "float",
                    "boolean": "bool",
                    "bool": "bool",
                }
                py_type = type_map.get(p_type, "str")
                if p_default is not None:
                    param_strs.append(f"{p_name}: {py_type} = {repr(p_default)}")
                else:
                    param_strs.append(f"{p_name}: {py_type}")

            params_str = ", ".join(param_strs)
            param_names = ", ".join(p.get("name", "arg") for p in params)

            func_code = f'''
@mcp.tool()
def {tool_name}({params_str}) -> str:
    """{tool_desc}"""
    # TODO: Implement {tool_name} logic
    return f"{tool_name} called with: {{{param_names}}}"
'''
            tool_functions.append(func_code)

        tools_code = "\n".join(tool_functions)

        server_py = f'''"""
MCP Server: {name}
{description}

Auto-generated by Micelia MCP Generator.
"""

from fastmcp import FastMCP

mcp = FastMCP("{name}")

{tools_code}

if __name__ == "__main__":
    mcp.run()
'''
        with open(server_dir / "server.py", "w") as f:
            f.write(server_py)

        # --- pyproject.toml ---
        pyproject = f'''[project]
name = "{name}"
version = "0.1.0"
description = "{description}"
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=2.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
{name} = "server:mcp.run"
'''
        with open(server_dir / "pyproject.toml", "w") as f:
            f.write(pyproject)

        # --- README.md ---
        tool_list = "\n".join(
            f"- **{t.get('name', 'unnamed')}**: {t.get('description', 'No description')}"
            for t in tools
        )
        readme = f"""# {name}

{description}

## Tools

{tool_list}

## Usage

```bash
# Install dependencies
pip install fastmcp

# Run the server
python server.py
```

## Generated by

Micelia MCP Generator
"""
        with open(server_dir / "README.md", "w") as f:
            f.write(readme)

    def _generate_typescript(
        self,
        server_dir: Path,
        name: str,
        description: str,
        tools: List[dict],
    ) -> None:
        """Genera servidor MCP en TypeScript con @modelcontextprotocol/sdk."""

        # --- server.ts ---
        tool_registrations = []

        for tool in tools:
            tool_name = tool.get("name", "unnamed_tool")
            tool_desc = tool.get("description", "No description")
            params = tool.get("parameters", [])

            # Build Zod schema properties
            schema_props = []
            for p in params:
                p_name = p.get("name", "arg")
                p_type = p.get("type", "string")
                type_map = {
                    "string": "z.string()",
                    "str": "z.string()",
                    "integer": "z.number().int()",
                    "int": "z.number().int()",
                    "number": "z.number()",
                    "float": "z.number()",
                    "boolean": "z.boolean()",
                    "bool": "z.boolean()",
                }
                zod_type = type_map.get(p_type, "z.string()")
                p_desc = p.get("description", "")
                schema_props.append(
                    f'    {p_name}: {zod_type}.describe("{p_desc}")'
                )

            schema_str = ",\n".join(schema_props)

            tool_registrations.append(f"""  server.tool(
    "{tool_name}",
    "{tool_desc}",
    {{
{schema_str}
    }},
    async ({{ {", ".join(p.get("name", "arg") for p in params)} }}) => {{
      // TODO: Implement {tool_name} logic
      return {{
        content: [{{ type: "text", text: `{tool_name} called successfully` }}],
      }};
    }}
  );""")

        registrations_code = "\n\n".join(tool_registrations)

        server_ts = f'''/**
 * MCP Server: {name}
 * {description}
 *
 * Auto-generated by Micelia MCP Generator.
 */

import {{ McpServer }} from "@modelcontextprotocol/sdk/server/mcp.js";
import {{ StdioServerTransport }} from "@modelcontextprotocol/sdk/server/stdio.js";
import {{ z }} from "zod";

const server = new McpServer({{
  name: "{name}",
  version: "0.1.0",
}});

// === Tool Registrations ===

{registrations_code}

// === Start Server ===

async function main() {{
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("{name} MCP server running on stdio");
}}

main().catch(console.error);
'''
        with open(server_dir / "server.ts", "w") as f:
            f.write(server_ts)

        # --- package.json ---
        package_json = {
            "name": name,
            "version": "0.1.0",
            "description": description,
            "type": "module",
            "main": "server.ts",
            "scripts": {
                "build": "tsc",
                "start": "npx tsx server.ts",
                "dev": "npx tsx --watch server.ts",
            },
            "dependencies": {
                "@modelcontextprotocol/sdk": "^1.0.0",
                "zod": "^3.22.0",
            },
            "devDependencies": {
                "typescript": "^5.3.0",
                "tsx": "^4.7.0",
                "@types/node": "^20.0.0",
            },
        }
        with open(server_dir / "package.json", "w") as f:
            json.dump(package_json, f, indent=2)

        # --- README.md ---
        tool_list = "\n".join(
            f"- **{t.get('name', 'unnamed')}**: {t.get('description', 'No description')}"
            for t in tools
        )
        readme = f"""# {name}

{description}

## Tools

{tool_list}

## Usage

```bash
# Install dependencies
npm install

# Run the server
npx tsx server.ts
```

## Generated by

Micelia MCP Generator
"""
        with open(server_dir / "README.md", "w") as f:
            f.write(readme)

    # ==================== MANAGEMENT ====================

    def list_servers(self) -> List[dict]:
        """Lista todos los servidores MCP generados."""
        servers: List[dict] = []
        if not self.output_dir.exists():
            return servers

        for entry in sorted(self.output_dir.iterdir()):
            if entry.is_dir():
                metadata_path = entry / "metadata.json"
                if metadata_path.exists():
                    try:
                        with open(metadata_path) as f:
                            meta = json.load(f)
                        meta["running"] = entry.name in self._running_processes
                        servers.append(meta)
                    except Exception as e:
                        log.warning(f"Failed to read metadata for {entry.name}: {e}")
                        servers.append({
                            "server_id": entry.name,
                            "description": "Unknown (metadata unreadable)",
                            "language": "unknown",
                            "tools_count": 0,
                            "running": entry.name in self._running_processes,
                        })
        return servers

    def get_server(self, server_id: str) -> dict:
        """
        Obtiene detalles de un servidor incluyendo código fuente.

        Args:
            server_id: ID del servidor

        Returns:
            dict con metadata y source_code

        Raises:
            FileNotFoundError: Si el servidor no existe
        """
        server_dir = self.output_dir / server_id
        if not server_dir.exists():
            raise FileNotFoundError(f"Server '{server_id}' not found")

        # Load metadata
        metadata_path = server_dir / "metadata.json"
        if metadata_path.exists():
            with open(metadata_path) as f:
                result = json.load(f)
        else:
            result = {"server_id": server_id}

        result["running"] = server_id in self._running_processes

        # Load source code
        language = result.get("language", "python")
        source_file = "server.py" if language == "python" else "server.ts"
        source_path = server_dir / source_file
        if source_path.exists():
            with open(source_path) as f:
                result["source_code"] = f.read()

        # List all files
        result["files"] = [
            str(p.relative_to(server_dir)) for p in server_dir.rglob("*") if p.is_file()
        ]

        return result

    def delete_server(self, server_id: str) -> None:
        """
        Elimina un servidor MCP y su directorio.

        Args:
            server_id: ID del servidor

        Raises:
            FileNotFoundError: Si el servidor no existe
            RuntimeError: Si el servidor está corriendo
        """
        server_dir = self.output_dir / server_id
        if not server_dir.exists():
            raise FileNotFoundError(f"Server '{server_id}' not found")

        if server_id in self._running_processes:
            raise RuntimeError(f"Server '{server_id}' is running. Stop it first.")

        shutil.rmtree(server_dir)
        log.info(f"MCP server deleted: {server_id}")

    # ==================== LIFECYCLE ====================

    def start_server(self, server_id: str) -> dict:
        """
        Inicia un servidor MCP como subproceso.

        Args:
            server_id: ID del servidor

        Returns:
            dict con pid y status

        Raises:
            FileNotFoundError: Si el servidor no existe
            RuntimeError: Si ya está corriendo
        """
        server_dir = self.output_dir / server_id
        if not server_dir.exists():
            raise FileNotFoundError(f"Server '{server_id}' not found")

        if server_id in self._running_processes:
            proc = self._running_processes[server_id]
            if proc.poll() is None:
                raise RuntimeError(f"Server '{server_id}' is already running (pid={proc.pid})")
            else:
                # Process terminated, clean up
                del self._running_processes[server_id]

        # Determine command
        metadata_path = server_dir / "metadata.json"
        language = "python"
        if metadata_path.exists():
            with open(metadata_path) as f:
                meta = json.load(f)
                language = meta.get("language", "python")

        if language == "python":
            cmd = ["python", "server.py"]
        else:
            cmd = ["npx", "tsx", "server.ts"]

        try:
            proc = subprocess.Popen(
                cmd,
                cwd=str(server_dir),
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                preexec_fn=os.setsid,
            )
            self._running_processes[server_id] = proc
            log.info(f"MCP server started: {server_id} (pid={proc.pid})")

            return {
                "server_id": server_id,
                "pid": proc.pid,
                "status": "running",
            }
        except Exception as e:
            log.error(f"Failed to start MCP server {server_id}: {e}")
            raise RuntimeError(f"Failed to start server: {e}")

    def stop_server(self, server_id: str) -> dict:
        """
        Detiene un servidor MCP en ejecución.

        Args:
            server_id: ID del servidor

        Returns:
            dict con status

        Raises:
            RuntimeError: Si el servidor no está corriendo
        """
        if server_id not in self._running_processes:
            raise RuntimeError(f"Server '{server_id}' is not running")

        proc = self._running_processes[server_id]

        if proc.poll() is not None:
            # Already terminated
            del self._running_processes[server_id]
            return {"server_id": server_id, "status": "already_stopped"}

        try:
            # Graceful shutdown: send SIGTERM to process group
            os.killpg(os.getpgid(proc.pid), signal.SIGTERM)
            try:
                proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                # Force kill
                os.killpg(os.getpgid(proc.pid), signal.SIGKILL)
                proc.wait(timeout=3)
        except ProcessLookupError:
            pass

        del self._running_processes[server_id]
        log.info(f"MCP server stopped: {server_id}")

        return {"server_id": server_id, "status": "stopped"}


# ==================== SINGLETON ====================

_mcp_generator: Optional[MCPGenerator] = None


def get_mcp_generator() -> MCPGenerator:
    """Singleton del generador MCP."""
    global _mcp_generator
    if _mcp_generator is None:
        _mcp_generator = MCPGenerator()
    return _mcp_generator
