"""
Tests for PolicyEngine, Budget, and PolicyDecision (app.services.frangels.policy_engine).

Generated by Codex CLI (gpt-5.4) -- comprehensive pytest test suite.

Covers:
  - Budget: can_spend, record_spend, auto_reset, to_dict
  - PolicyEngine.evaluate for all 5 policy types
  - Category overrides
  - Budget cap exhaustion scenario
  - set_budget and set_category_policy
  - get_status
  - PolicyDecision dataclass defaults
  - ProviderRoute dataclass
  - Singleton get_policy_engine
"""

from datetime import date, timedelta

import pytest

import app.services.frangels.policy_engine as policy_module
from app.services.frangels.policy_engine import (
    PRIVACY_SENSITIVE,
    SENSITIVE_CATEGORIES,
    WORK_CATEGORIES,
    Budget,
    PolicyDecision,
    PolicyEngine,
    PolicyType,
    ProviderRoute,
    get_policy_engine,
)

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture
def budget():
    """Fresh Budget with default limits."""
    return Budget()


@pytest.fixture
def engine():
    """Fresh PolicyEngine with default budget."""
    return PolicyEngine()


@pytest.fixture(autouse=True)
def reset_singleton():
    """Reset the module-level singleton between tests."""
    policy_module._policy_engine = None
    yield
    policy_module._policy_engine = None


# ---------------------------------------------------------------------------
# Budget Tests
# ---------------------------------------------------------------------------

class TestBudget:

    def test_defaults(self, budget):
        assert budget.daily_limit_usd == 5.0
        assert budget.monthly_limit_usd == 50.0
        assert budget.spent_today_usd == 0.0
        assert budget.spent_this_month_usd == 0.0
        assert budget.last_reset_date is None
        assert budget.last_reset_month is None

    def test_can_spend_within_daily_limit(self, budget):
        assert budget.can_spend(1.0) is True
        assert budget.can_spend(5.0) is True

    def test_can_spend_at_exact_daily_limit(self, budget):
        """Spending exactly the daily limit should be allowed (<=)."""
        assert budget.can_spend(5.0) is True

    def test_can_spend_exceeds_daily_limit(self, budget):
        assert budget.can_spend(5.01) is False

    def test_can_spend_exceeds_monthly_limit(self):
        b = Budget(daily_limit_usd=100.0, monthly_limit_usd=10.0)
        assert b.can_spend(10.0) is True
        assert b.can_spend(10.01) is False

    def test_can_spend_zero(self, budget):
        assert budget.can_spend(0.0) is True

    def test_record_spend_updates_both_counters(self, budget):
        budget.record_spend(2.0)
        # After auto_reset, last_reset_date is set to today
        assert budget.spent_today_usd == 2.0
        assert budget.spent_this_month_usd == 2.0

    def test_record_spend_multiple(self, budget):
        budget.record_spend(1.0)
        budget.record_spend(1.5)
        budget.record_spend(0.5)
        assert budget.can_spend(2.0) is True
        assert budget.can_spend(2.01) is False

    def test_record_spend_then_can_spend_checks_correctly(self, budget):
        budget.record_spend(4.0)
        assert budget.can_spend(1.0) is True
        assert budget.can_spend(1.01) is False

    def test_auto_reset_daily(self):
        """When last_reset_date is yesterday, daily counter resets."""
        b = Budget()
        yesterday = date.today() - timedelta(days=1)
        b.last_reset_date = yesterday
        b.last_reset_month = date.today().month
        b.spent_today_usd = 4.99
        b.spent_this_month_usd = 10.0

        # can_spend triggers _auto_reset; daily should reset to 0
        assert b.can_spend(5.0) is True
        assert b.spent_today_usd == 0.0  # was reset
        # Monthly should NOT have reset (same month)
        assert b.spent_this_month_usd == 10.0

    def test_auto_reset_monthly(self):
        """When last_reset_month differs, monthly counter resets."""
        b = Budget(daily_limit_usd=100.0, monthly_limit_usd=50.0)
        today = date.today()
        b.last_reset_date = today  # same day, so daily doesn't reset
        # Set to a different month
        different_month = (today.month % 12) + 1
        b.last_reset_month = different_month
        b.spent_today_usd = 2.0
        b.spent_this_month_usd = 49.0

        assert b.can_spend(50.0) is True
        assert b.spent_this_month_usd == 0.0  # was reset

    def test_auto_reset_both_when_none(self):
        """First call with None dates triggers reset for both."""
        b = Budget()
        b.spent_today_usd = 99.0
        b.spent_this_month_usd = 99.0
        assert b.last_reset_date is None
        assert b.last_reset_month is None

        # Calling can_spend triggers _auto_reset which resets because None != today
        assert b.can_spend(5.0) is True

    def test_to_dict_structure(self, budget):
        result = budget.to_dict()
        expected_keys = {
            "daily_limit_usd",
            "monthly_limit_usd",
            "spent_today_usd",
            "spent_this_month_usd",
            "remaining_today_usd",
            "remaining_month_usd",
        }
        assert set(result.keys()) == expected_keys

    def test_to_dict_values_fresh(self, budget):
        result = budget.to_dict()
        assert result["daily_limit_usd"] == 5.0
        assert result["monthly_limit_usd"] == 50.0
        assert result["spent_today_usd"] == 0.0
        assert result["spent_this_month_usd"] == 0.0
        assert result["remaining_today_usd"] == 5.0
        assert result["remaining_month_usd"] == 50.0

    def test_to_dict_after_spending(self, budget):
        budget.record_spend(1.5)
        result = budget.to_dict()
        assert result["spent_today_usd"] == 1.5
        assert result["spent_this_month_usd"] == 1.5
        assert result["remaining_today_usd"] == 3.5
        assert result["remaining_month_usd"] == 48.5

    def test_to_dict_rounds_to_4_decimals(self):
        b = Budget(daily_limit_usd=10.0, monthly_limit_usd=100.0)
        b.record_spend(1.123456789)
        result = b.to_dict()
        assert result["spent_today_usd"] == round(1.123456789, 4)
        assert result["spent_this_month_usd"] == round(1.123456789, 4)

    def test_can_spend_respects_both_limits(self):
        """Must be within BOTH daily AND monthly to allow spend."""
        b = Budget(daily_limit_usd=10.0, monthly_limit_usd=5.0)
        # Daily allows it, but monthly doesn't
        assert b.can_spend(6.0) is False

    def test_custom_limits(self):
        b = Budget(daily_limit_usd=100.0, monthly_limit_usd=500.0)
        assert b.daily_limit_usd == 100.0
        assert b.monthly_limit_usd == 500.0
        assert b.can_spend(100.0) is True
        assert b.can_spend(100.01) is False


# ---------------------------------------------------------------------------
# PolicyDecision Tests
# ---------------------------------------------------------------------------

class TestPolicyDecision:

    def test_defaults(self):
        d = PolicyDecision()
        assert d.prefer_paid is False
        assert d.force_free is False
        assert d.require_different_reviewer is False
        assert d.allowed_providers is None
        assert d.blocked_providers is None
        assert d.budget_available is True
        assert d.reason == ""

    def test_custom_values(self):
        d = PolicyDecision(
            prefer_paid=True,
            force_free=False,
            require_different_reviewer=True,
            allowed_providers=["local"],
            blocked_providers=["openai"],
            budget_available=False,
            reason="test reason",
        )
        assert d.prefer_paid is True
        assert d.require_different_reviewer is True
        assert d.allowed_providers == ["local"]
        assert d.blocked_providers == ["openai"]
        assert d.budget_available is False
        assert d.reason == "test reason"


# ---------------------------------------------------------------------------
# ProviderRoute Tests
# ---------------------------------------------------------------------------

class TestProviderRoute:

    def test_defaults(self):
        r = ProviderRoute(provider_id="local-1", is_paid=False, policy_applied="free-first")
        assert r.provider_id == "local-1"
        assert r.is_paid is False
        assert r.policy_applied == "free-first"
        assert r.fallback_chain == []

    def test_with_fallback_chain(self):
        r = ProviderRoute(
            provider_id="openai",
            is_paid=True,
            policy_applied="paid-for-work",
            fallback_chain=["anthropic", "local"],
        )
        assert r.fallback_chain == ["anthropic", "local"]


# ---------------------------------------------------------------------------
# PolicyType Enum Tests
# ---------------------------------------------------------------------------

class TestPolicyType:

    def test_all_values(self):
        assert PolicyType.FREE_FIRST.value == "free-first"
        assert PolicyType.PAID_FOR_WORK.value == "paid-for-work"
        assert PolicyType.CRITICAL_REVIEWED.value == "critical-reviewed"
        assert PolicyType.PRIVACY_HIGH.value == "privacy-high"
        assert PolicyType.BUDGET_CAP.value == "budget-cap"

    def test_from_string(self):
        assert PolicyType("free-first") == PolicyType.FREE_FIRST
        assert PolicyType("budget-cap") == PolicyType.BUDGET_CAP

    def test_invalid_raises(self):
        with pytest.raises(ValueError):
            PolicyType("nonexistent-policy")

    def test_is_str_subclass(self):
        assert isinstance(PolicyType.FREE_FIRST, str)


# ---------------------------------------------------------------------------
# Category Sets Tests
# ---------------------------------------------------------------------------

class TestCategorySets:

    def test_work_categories(self):
        assert WORK_CATEGORIES == {"work", "plan", "project"}

    def test_sensitive_categories(self):
        assert SENSITIVE_CATEGORIES == {"work", "plan", "project", "personal"}

    def test_privacy_sensitive(self):
        assert PRIVACY_SENSITIVE == {"personal", "health"}


# ---------------------------------------------------------------------------
# PolicyEngine.evaluate Tests — all 5 policy types
# ---------------------------------------------------------------------------

class TestPolicyEngineEvaluateFreeFirst:

    def test_free_first_default(self, engine):
        """Default policy is free-first when no provider_policy specified."""
        decision = engine.evaluate({"category": "note"})
        assert decision.prefer_paid is False
        assert decision.force_free is True
        assert decision.reason == "Free-first: using free providers"

    def test_free_first_explicit(self, engine):
        decision = engine.evaluate({
            "category": "note",
            "provider_policy": "free-first",
        })
        assert decision.prefer_paid is False
        assert decision.force_free is True

    def test_free_first_any_category(self, engine):
        for cat in ["note", "work", "personal", "health", "random"]:
            decision = engine.evaluate({
                "category": cat,
                "provider_policy": "free-first",
            })
            assert decision.force_free is True


class TestPolicyEngineEvaluatePaidForWork:

    def test_work_category_uses_paid(self, engine):
        decision = engine.evaluate({
            "category": "work",
            "provider_policy": "paid-for-work",
        })
        assert decision.prefer_paid is True
        assert decision.force_free is False
        assert "paid" in decision.reason.lower()

    def test_plan_category_uses_paid(self, engine):
        decision = engine.evaluate({
            "category": "plan",
            "provider_policy": "paid-for-work",
        })
        assert decision.prefer_paid is True

    def test_project_category_uses_paid(self, engine):
        decision = engine.evaluate({
            "category": "project",
            "provider_policy": "paid-for-work",
        })
        assert decision.prefer_paid is True

    def test_non_work_category_stays_free(self, engine):
        decision = engine.evaluate({
            "category": "note",
            "provider_policy": "paid-for-work",
        })
        assert decision.prefer_paid is False
        assert decision.force_free is True
        assert "stays free" in decision.reason.lower()

    def test_personal_category_stays_free(self, engine):
        decision = engine.evaluate({
            "category": "personal",
            "provider_policy": "paid-for-work",
        })
        assert decision.force_free is True


class TestPolicyEngineEvaluateCriticalReviewed:

    def test_critical_reviewed_basic(self, engine):
        decision = engine.evaluate({
            "category": "plan",
            "provider_policy": "critical-reviewed",
        })
        assert decision.prefer_paid is True
        assert decision.require_different_reviewer is True
        assert "critical" in decision.reason.lower()
        assert "reviewer" in decision.reason.lower()

    def test_critical_reviewed_any_category(self, engine):
        """Critical-reviewed applies regardless of category."""
        for cat in ["note", "work", "personal"]:
            decision = engine.evaluate({
                "category": cat,
                "provider_policy": "critical-reviewed",
            })
            assert decision.prefer_paid is True
            assert decision.require_different_reviewer is True


class TestPolicyEngineEvaluatePrivacyHigh:

    def test_privacy_high_blocks_major_providers(self, engine):
        decision = engine.evaluate({
            "category": "personal",
            "provider_policy": "privacy-high",
        })
        assert decision.prefer_paid is False
        assert decision.blocked_providers == ["openai", "anthropic"]
        assert "privacy" in decision.reason.lower()

    def test_privacy_high_does_not_force_free(self, engine):
        """Privacy-high blocks providers but does not set force_free."""
        decision = engine.evaluate({
            "category": "health",
            "provider_policy": "privacy-high",
        })
        assert decision.force_free is False

    def test_privacy_high_budget_still_available(self, engine):
        decision = engine.evaluate({
            "category": "personal",
            "provider_policy": "privacy-high",
        })
        assert decision.budget_available is True


class TestPolicyEngineEvaluateBudgetCap:

    def test_budget_cap_within_budget(self, engine):
        decision = engine.evaluate({
            "category": "note",
            "provider_policy": "budget-cap",
        })
        assert decision.prefer_paid is True
        assert decision.budget_available is True
        assert decision.force_free is False

    def test_budget_cap_exhausted_daily(self):
        """When daily budget is exhausted, force free."""
        engine = PolicyEngine()
        engine.budget.daily_limit_usd = 0.005
        # Spend up to the limit
        engine.budget.record_spend(0.005)

        decision = engine.evaluate({
            "category": "note",
            "provider_policy": "budget-cap",
        })
        assert decision.prefer_paid is False
        assert decision.force_free is True
        assert decision.budget_available is False
        assert "limit reached" in decision.reason.lower()

    def test_budget_cap_exhausted_monthly(self):
        """When monthly budget is exhausted, force free."""
        engine = PolicyEngine()
        engine.budget.daily_limit_usd = 100.0
        engine.budget.monthly_limit_usd = 0.004
        engine.budget.record_spend(0.004)

        decision = engine.evaluate({
            "category": "note",
            "provider_policy": "budget-cap",
        })
        assert decision.force_free is True
        assert decision.budget_available is False

    def test_budget_cap_reason_includes_spent_info(self, engine):
        decision = engine.evaluate({
            "category": "note",
            "provider_policy": "budget-cap",
        })
        # When within budget, reason includes spend stats
        assert "$" in decision.reason
        assert "daily" in decision.reason.lower()


# ---------------------------------------------------------------------------
# Unknown / invalid policy
# ---------------------------------------------------------------------------

class TestPolicyEngineEvaluateUnknown:

    def test_unknown_policy_falls_back_to_free_first(self, engine):
        decision = engine.evaluate({
            "category": "note",
            "provider_policy": "nonexistent-policy-xyz",
        })
        assert decision.prefer_paid is False
        assert decision.force_free is True
        assert decision.reason == "Free-first: using free providers"

    def test_missing_provider_policy_defaults_free_first(self, engine):
        decision = engine.evaluate({"category": "note"})
        assert decision.force_free is True

    def test_missing_category_defaults_note(self, engine):
        decision = engine.evaluate({"provider_policy": "free-first"})
        assert decision.force_free is True

    def test_empty_prompt(self, engine):
        decision = engine.evaluate({})
        assert decision.force_free is True


# ---------------------------------------------------------------------------
# Category overrides
# ---------------------------------------------------------------------------

class TestCategoryOverrides:

    def test_override_overrides_prompt_policy(self, engine):
        """Category override takes precedence over provider_policy in prompt."""
        engine.set_category_policy("note", "paid-for-work")
        decision = engine.evaluate({
            "category": "note",
            "provider_policy": "free-first",
        })
        # "note" is NOT in WORK_CATEGORIES, so paid-for-work => stays free
        assert decision.force_free is True

    def test_override_work_to_privacy_high(self, engine):
        engine.set_category_policy("work", "privacy-high")
        decision = engine.evaluate({
            "category": "work",
            "provider_policy": "paid-for-work",
        })
        assert decision.blocked_providers == ["openai", "anthropic"]
        assert decision.prefer_paid is False

    def test_override_to_critical_reviewed(self, engine):
        engine.set_category_policy("personal", "critical-reviewed")
        decision = engine.evaluate({
            "category": "personal",
            "provider_policy": "free-first",
        })
        assert decision.prefer_paid is True
        assert decision.require_different_reviewer is True

    def test_override_does_not_affect_other_categories(self, engine):
        engine.set_category_policy("work", "privacy-high")
        decision = engine.evaluate({
            "category": "note",
            "provider_policy": "free-first",
        })
        assert decision.force_free is True
        assert decision.blocked_providers is None

    def test_override_can_be_replaced(self, engine):
        engine.set_category_policy("work", "privacy-high")
        engine.set_category_policy("work", "free-first")
        decision = engine.evaluate({
            "category": "work",
            "provider_policy": "paid-for-work",
        })
        assert decision.force_free is True

    def test_multiple_overrides(self, engine):
        engine.set_category_policy("work", "critical-reviewed")
        engine.set_category_policy("personal", "privacy-high")
        engine.set_category_policy("note", "budget-cap")

        d_work = engine.evaluate({"category": "work"})
        assert d_work.require_different_reviewer is True

        d_personal = engine.evaluate({"category": "personal"})
        assert d_personal.blocked_providers == ["openai", "anthropic"]

        d_note = engine.evaluate({"category": "note"})
        assert d_note.budget_available is True


# ---------------------------------------------------------------------------
# set_budget
# ---------------------------------------------------------------------------

class TestSetBudget:

    def test_set_daily_only(self, engine):
        engine.set_budget(daily=20.0)
        assert engine.budget.daily_limit_usd == 20.0
        assert engine.budget.monthly_limit_usd == 50.0  # unchanged

    def test_set_monthly_only(self, engine):
        engine.set_budget(monthly=200.0)
        assert engine.budget.monthly_limit_usd == 200.0
        assert engine.budget.daily_limit_usd == 5.0  # unchanged

    def test_set_both(self, engine):
        engine.set_budget(daily=15.0, monthly=300.0)
        assert engine.budget.daily_limit_usd == 15.0
        assert engine.budget.monthly_limit_usd == 300.0

    def test_set_budget_none_params_no_change(self, engine):
        engine.set_budget()  # no args
        assert engine.budget.daily_limit_usd == 5.0
        assert engine.budget.monthly_limit_usd == 50.0

    def test_set_budget_affects_evaluate(self, engine):
        engine.set_budget(daily=0.001)
        engine.budget.record_spend(0.001)
        decision = engine.evaluate({
            "category": "note",
            "provider_policy": "budget-cap",
        })
        assert decision.budget_available is False


# ---------------------------------------------------------------------------
# record_cost
# ---------------------------------------------------------------------------

class TestRecordCost:

    def test_record_cost_delegates_to_budget(self, engine):
        engine.record_cost(1.5)
        assert engine.budget.spent_today_usd == 1.5
        assert engine.budget.spent_this_month_usd == 1.5

    def test_record_cost_multiple(self, engine):
        engine.record_cost(0.1)
        engine.record_cost(0.2)
        engine.record_cost(0.3)
        expected = round(0.1 + 0.2 + 0.3, 4)
        assert round(engine.budget.spent_today_usd, 4) == expected


# ---------------------------------------------------------------------------
# get_status
# ---------------------------------------------------------------------------

class TestGetStatus:

    def test_get_status_structure(self, engine):
        status = engine.get_status()
        assert "budget" in status
        assert "category_overrides" in status
        assert "available_policies" in status

    def test_get_status_budget_is_dict(self, engine):
        status = engine.get_status()
        budget = status["budget"]
        assert isinstance(budget, dict)
        assert "daily_limit_usd" in budget
        assert "remaining_today_usd" in budget

    def test_get_status_available_policies(self, engine):
        status = engine.get_status()
        policies = status["available_policies"]
        assert "free-first" in policies
        assert "paid-for-work" in policies
        assert "critical-reviewed" in policies
        assert "privacy-high" in policies
        assert "budget-cap" in policies
        assert len(policies) == 5

    def test_get_status_category_overrides_empty(self, engine):
        status = engine.get_status()
        assert status["category_overrides"] == {}

    def test_get_status_category_overrides_populated(self, engine):
        engine.set_category_policy("work", "privacy-high")
        engine.set_category_policy("note", "budget-cap")
        status = engine.get_status()
        assert status["category_overrides"] == {
            "work": "privacy-high",
            "note": "budget-cap",
        }

    def test_get_status_reflects_spending(self, engine):
        engine.record_cost(2.0)
        status = engine.get_status()
        assert status["budget"]["spent_today_usd"] == 2.0
        assert status["budget"]["remaining_today_usd"] == 3.0


# ---------------------------------------------------------------------------
# Singleton get_policy_engine
# ---------------------------------------------------------------------------

class TestSingleton:

    def test_creates_instance(self):
        eng = get_policy_engine()
        assert isinstance(eng, PolicyEngine)

    def test_returns_same_instance(self):
        eng1 = get_policy_engine()
        eng2 = get_policy_engine()
        assert eng1 is eng2

    def test_after_reset_creates_new(self):
        eng1 = get_policy_engine()
        policy_module._policy_engine = None
        eng2 = get_policy_engine()
        assert eng1 is not eng2


# ---------------------------------------------------------------------------
# Integration / workflow tests
# ---------------------------------------------------------------------------

class TestPolicyEngineIntegration:

    def test_budget_cap_exhaustion_workflow(self):
        """Simulate spending until budget is exhausted."""
        engine = PolicyEngine()
        engine.set_budget(daily=0.015, monthly=100.0)

        # First 3 requests (each estimated at $0.005) should pass
        for _ in range(3):
            decision = engine.evaluate({
                "category": "note",
                "provider_policy": "budget-cap",
            })
            assert decision.budget_available is True
            engine.record_cost(0.005)

        # 4th request: budget exhausted
        decision = engine.evaluate({
            "category": "note",
            "provider_policy": "budget-cap",
        })
        assert decision.budget_available is False
        assert decision.force_free is True

    def test_category_override_then_budget_check(self):
        """Override a category to budget-cap, then exhaust budget."""
        engine = PolicyEngine()
        # Daily limit must be >= estimated cost per request ($0.005)
        engine.set_budget(daily=0.01)
        engine.set_category_policy("work", "budget-cap")

        # Work category now uses budget-cap; should be available initially
        d1 = engine.evaluate({"category": "work", "provider_policy": "paid-for-work"})
        assert d1.prefer_paid is True
        assert d1.budget_available is True

        # Exhaust budget (spend enough so that $0.005 more won't fit)
        engine.record_cost(0.006)
        d2 = engine.evaluate({"category": "work", "provider_policy": "paid-for-work"})
        assert d2.force_free is True
        assert d2.budget_available is False

    def test_privacy_ignores_budget(self):
        """Privacy-high always blocks major providers regardless of budget."""
        engine = PolicyEngine()
        engine.set_budget(daily=1000.0, monthly=10000.0)
        decision = engine.evaluate({
            "category": "personal",
            "provider_policy": "privacy-high",
        })
        assert decision.blocked_providers == ["openai", "anthropic"]
        assert decision.budget_available is True
