"""
Tests for OSAScriptService (app.services.osascript).

Generated by Codex CLI -- comprehensive pytest test suite (Ciclo 26).

The whole module wraps ``subprocess.run`` and parses the resulting stdout, so
it is fully testable without a real macOS host:

* The dedicated helper/verify tests patch ``osa.subprocess.run`` to exercise the
  4 branches of ``_run_applescript`` / ``_run_applescript_file`` and the
  degrade-gracefully behaviour of ``_verify_osascript``.
* The ~30 public methods are tested by patching the instance helper
  (``_run_applescript`` / ``_run_applescript_file``) to return a canned string
  or raise ``OSAScriptError``, which isolates the parse/degradation logic and
  the AppleScript that each method builds.
"""

import subprocess
from datetime import datetime
from unittest.mock import patch

import pytest

import app.services.osascript as osa
from app.services.osascript import (
    CalendarEvent,
    Note,
    OSAScriptError,
    OSAScriptService,
    Reminder,
)

# ---------------------------------------------------------------------------
# Helpers & fixtures
# ---------------------------------------------------------------------------


def _completed(stdout="", returncode=0, stderr=""):
    """Build a fake subprocess.CompletedProcess."""
    return subprocess.CompletedProcess(
        args=[], returncode=returncode, stdout=stdout, stderr=stderr
    )


@pytest.fixture
def svc():
    """OSAScriptService instance built with subprocess.run neutralised.

    Keeps __init__ (which shells out to ``which osascript``) hermetic so the
    suite never depends on the host.
    """
    with patch.object(osa.subprocess, "run", return_value=_completed("", 0)):
        return OSAScriptService()


# ---------------------------------------------------------------------------
# _verify_osascript / __init__
# ---------------------------------------------------------------------------


class TestVerifyAndInit:
    def test_init_rc0_ok(self):
        with patch.object(osa.subprocess, "run", return_value=_completed("", 0)):
            service = OSAScriptService()
        assert isinstance(service, OSAScriptService)

    def test_init_rc_nonzero_warns_but_does_not_raise(self):
        with patch.object(osa.subprocess, "run", return_value=_completed("", 1)):
            with patch.object(osa.log, "warning") as warn:
                service = OSAScriptService()
        assert isinstance(service, OSAScriptService)
        warn.assert_called_once()

    def test_init_subprocess_raises_warns(self):
        with patch.object(osa.subprocess, "run", side_effect=OSError("no exec")):
            with patch.object(osa.log, "warning") as warn:
                service = OSAScriptService()
        assert isinstance(service, OSAScriptService)
        warn.assert_called_once()

    def test_module_singleton_exists(self):
        assert isinstance(osa.osascript_service, OSAScriptService)


# ---------------------------------------------------------------------------
# _run_applescript (osascript -e)
# ---------------------------------------------------------------------------


class TestRunApplescript:
    def test_success_strips_and_builds_command(self, svc):
        with patch.object(
            osa.subprocess, "run", return_value=_completed("  hi \n")
        ) as run:
            out = svc._run_applescript("beep", timeout=12)
        assert out == "hi"
        args, kwargs = run.call_args
        assert args[0] == ["osascript", "-e", "beep"]
        assert kwargs["capture_output"] is True
        assert kwargs["text"] is True
        assert kwargs["timeout"] == 12

    def test_nonzero_raises_osascript_error_with_stderr(self, svc):
        with patch.object(
            osa.subprocess, "run", return_value=_completed("", 1, "  boom  ")
        ):
            with pytest.raises(OSAScriptError) as exc:
                svc._run_applescript("x")
        assert "boom" in str(exc.value)

    def test_timeout_raises(self, svc):
        with patch.object(
            osa.subprocess,
            "run",
            side_effect=subprocess.TimeoutExpired(cmd="osascript", timeout=30),
        ):
            with pytest.raises(OSAScriptError) as exc:
                svc._run_applescript("x", timeout=30)
        assert "timed out" in str(exc.value)

    def test_generic_exception_raises(self, svc):
        with patch.object(osa.subprocess, "run", side_effect=RuntimeError("weird")):
            with pytest.raises(OSAScriptError) as exc:
                svc._run_applescript("x")
        assert "weird" in str(exc.value)


# ---------------------------------------------------------------------------
# _run_applescript_file (osascript, script via stdin)
# ---------------------------------------------------------------------------


class TestRunApplescriptFile:
    def test_success_uses_stdin(self, svc):
        with patch.object(
            osa.subprocess, "run", return_value=_completed("ok\n")
        ) as run:
            out = svc._run_applescript_file("multi\nline", timeout=7)
        assert out == "ok"
        args, kwargs = run.call_args
        assert args[0] == ["osascript"]
        assert kwargs["input"] == "multi\nline"
        assert kwargs["timeout"] == 7

    def test_nonzero_raises(self, svc):
        with patch.object(
            osa.subprocess, "run", return_value=_completed("", 2, "err")
        ):
            with pytest.raises(OSAScriptError):
                svc._run_applescript_file("x")

    def test_timeout_raises(self, svc):
        with patch.object(
            osa.subprocess,
            "run",
            side_effect=subprocess.TimeoutExpired(cmd="osascript", timeout=5),
        ):
            with pytest.raises(OSAScriptError) as exc:
                svc._run_applescript_file("x", timeout=5)
        assert "timed out" in str(exc.value)

    def test_generic_exception_raises(self, svc):
        with patch.object(osa.subprocess, "run", side_effect=ValueError("bad")):
            with pytest.raises(OSAScriptError) as exc:
                svc._run_applescript_file("x")
        assert "bad" in str(exc.value)


# ---------------------------------------------------------------------------
# Sistema
# ---------------------------------------------------------------------------


class TestSystem:
    def test_get_system_info_full(self, svc):
        with patch.object(svc, "_run_applescript_file", return_value="bob|macbook|arm"):
            info = svc.get_system_info()
        assert info == {
            "user_name": "bob",
            "computer_name": "macbook",
            "cpu_type": "arm",
        }

    def test_get_system_info_short(self, svc):
        with patch.object(svc, "_run_applescript_file", return_value="onlyuser"):
            info = svc.get_system_info()
        assert info["user_name"] == "onlyuser"
        assert info["computer_name"] is None
        assert info["cpu_type"] is None

    def test_get_frontmost_app(self, svc):
        with patch.object(svc, "_run_applescript_file", return_value="Safari"):
            assert svc.get_frontmost_app() == "Safari"

    def test_get_running_apps(self, svc):
        with patch.object(
            svc, "_run_applescript_file", return_value="Safari|||Notes|||"
        ):
            assert svc.get_running_apps() == ["Safari", "Notes"]

    def test_get_running_apps_empty(self, svc):
        with patch.object(svc, "_run_applescript_file", return_value=""):
            assert svc.get_running_apps() == []

    def test_send_notification_success(self, svc):
        with patch.object(svc, "_run_applescript_file", return_value=""):
            assert svc.send_notification("Title", "Body") is True

    def test_send_notification_with_subtitle_in_script(self, svc):
        with patch.object(svc, "_run_applescript_file", return_value="") as m:
            svc.send_notification("T", "M", subtitle="Sub")
        script = m.call_args.args[0]
        assert 'subtitle "Sub"' in script

    def test_send_notification_failure(self, svc):
        with patch.object(
            svc, "_run_applescript_file", side_effect=OSAScriptError("x")
        ):
            assert svc.send_notification("T", "M") is False

    def test_say_text_success(self, svc):
        with patch.object(svc, "_run_applescript", return_value=""):
            assert svc.say_text("hola") is True

    def test_say_text_failure(self, svc):
        with patch.object(svc, "_run_applescript", side_effect=OSAScriptError("x")):
            assert svc.say_text("hola") is False

    def test_get_volume(self, svc):
        with patch.object(svc, "_run_applescript", return_value="42"):
            assert svc.get_volume() == 42

    def test_set_volume_clamps_high(self, svc):
        with patch.object(svc, "_run_applescript", return_value="") as m:
            assert svc.set_volume(150) is True
        assert "100" in m.call_args.args[0]

    def test_set_volume_clamps_low(self, svc):
        with patch.object(svc, "_run_applescript", return_value="") as m:
            assert svc.set_volume(-5) is True
        assert "output volume 0" in m.call_args.args[0]

    def test_set_volume_failure(self, svc):
        with patch.object(svc, "_run_applescript", side_effect=OSAScriptError("x")):
            assert svc.set_volume(50) is False

    def test_toggle_dark_mode_success(self, svc):
        with patch.object(svc, "_run_applescript_file", return_value=""):
            assert svc.toggle_dark_mode() is True

    def test_toggle_dark_mode_failure(self, svc):
        with patch.object(
            svc, "_run_applescript_file", side_effect=OSAScriptError("x")
        ):
            assert svc.toggle_dark_mode() is False

    def test_is_dark_mode_true(self, svc):
        with patch.object(svc, "_run_applescript_file", return_value="true"):
            assert svc.is_dark_mode() is True

    def test_is_dark_mode_false(self, svc):
        with patch.object(svc, "_run_applescript_file", return_value="false"):
            assert svc.is_dark_mode() is False


# ---------------------------------------------------------------------------
# Calendario
# ---------------------------------------------------------------------------


class TestCalendar:
    def test_get_calendars(self, svc):
        with patch.object(
            svc, "_run_applescript_file", return_value="Work|||Home|||"
        ):
            assert svc.get_calendars() == ["Work", "Home"]

    def test_get_today_events_all(self, svc):
        raw = "Meeting|2026-07-12 10:00:00|2026-07-12 11:00:00|Office"
        with patch.object(svc, "_run_applescript_file", return_value=raw):
            events = svc.get_today_events()
        assert events == [
            {
                "title": "Meeting",
                "start": "2026-07-12 10:00:00",
                "end": "2026-07-12 11:00:00",
                "location": "Office",
            }
        ]

    def test_get_today_events_named_calendar_in_script(self, svc):
        with patch.object(svc, "_run_applescript_file", return_value="") as m:
            svc.get_today_events(calendar_name="Work")
        assert 'calendar "Work"' in m.call_args.args[0]

    def test_get_today_events_empty(self, svc):
        with patch.object(svc, "_run_applescript_file", return_value=""):
            assert svc.get_today_events() == []

    def test_get_today_events_error_returns_empty(self, svc):
        with patch.object(
            svc, "_run_applescript_file", side_effect=OSAScriptError("x")
        ):
            assert svc.get_today_events() == []

    def test_create_calendar_event_minimal(self, svc):
        event = CalendarEvent(
            title="Standup",
            start_date=datetime(2026, 7, 12, 9, 0),
            end_date=datetime(2026, 7, 12, 9, 30),
        )
        with patch.object(svc, "_run_applescript_file", return_value=""):
            assert svc.create_calendar_event(event) is True

    def test_create_calendar_event_with_location_and_notes(self, svc):
        event = CalendarEvent(
            title="Standup",
            start_date=datetime(2026, 7, 12, 9, 0),
            end_date=datetime(2026, 7, 12, 9, 30),
            location="Room 5",
            notes="daily",
        )
        with patch.object(svc, "_run_applescript_file", return_value="") as m:
            svc.create_calendar_event(event)
        script = m.call_args.args[0]
        assert "Room 5" in script
        assert "daily" in script

    def test_create_calendar_event_failure(self, svc):
        event = CalendarEvent(
            title="X",
            start_date=datetime(2026, 7, 12, 9, 0),
            end_date=datetime(2026, 7, 12, 9, 30),
        )
        with patch.object(
            svc, "_run_applescript_file", side_effect=OSAScriptError("x")
        ):
            assert svc.create_calendar_event(event) is False


# ---------------------------------------------------------------------------
# Recordatorios
# ---------------------------------------------------------------------------


class TestReminders:
    def test_get_reminder_lists(self, svc):
        with patch.object(
            svc, "_run_applescript_file", return_value="Personal|||Work|||"
        ):
            assert svc.get_reminder_lists() == ["Personal", "Work"]

    def test_get_reminders_all(self, svc):
        raw = "Buy milk|2026-07-12|false, Call mom|missing value|true"
        with patch.object(svc, "_run_applescript_file", return_value=raw):
            rems = svc.get_reminders()
        assert rems[0] == {
            "name": "Buy milk",
            "due_date": "2026-07-12",
            "completed": False,
        }
        assert rems[1]["name"] == "Call mom"
        assert rems[1]["completed"] is True

    def test_get_reminders_named_list_applies_filter(self, svc):
        with patch.object(svc, "_run_applescript_file", return_value="") as m:
            svc.get_reminders(list_name="Personal", include_completed=False)
        script = m.call_args.args[0]
        assert 'list "Personal"' in script
        assert "whose completed is false" in script

    def test_get_reminders_include_completed_no_filter(self, svc):
        with patch.object(svc, "_run_applescript_file", return_value="") as m:
            svc.get_reminders(list_name="Personal", include_completed=True)
        assert "whose completed is false" not in m.call_args.args[0]

    def test_get_reminders_error_returns_empty(self, svc):
        with patch.object(
            svc, "_run_applescript_file", side_effect=OSAScriptError("x")
        ):
            assert svc.get_reminders() == []

    def test_create_reminder_minimal(self, svc):
        with patch.object(svc, "_run_applescript_file", return_value=""):
            assert svc.create_reminder(Reminder(name="Task")) is True

    def test_create_reminder_with_due_and_notes(self, svc):
        reminder = Reminder(
            name="Task",
            due_date=datetime(2026, 7, 12, 15, 0),
            notes="ping",
        )
        with patch.object(svc, "_run_applescript_file", return_value="") as m:
            svc.create_reminder(reminder)
        script = m.call_args.args[0]
        assert "due date:date" in script
        assert "ping" in script

    def test_create_reminder_failure(self, svc):
        with patch.object(
            svc, "_run_applescript_file", side_effect=OSAScriptError("x")
        ):
            assert svc.create_reminder(Reminder(name="Task")) is False

    def test_complete_reminder_success(self, svc):
        with patch.object(svc, "_run_applescript_file", return_value=""):
            assert svc.complete_reminder("Task") is True

    def test_complete_reminder_failure(self, svc):
        with patch.object(
            svc, "_run_applescript_file", side_effect=OSAScriptError("x")
        ):
            assert svc.complete_reminder("Task") is False


# ---------------------------------------------------------------------------
# Notas
# ---------------------------------------------------------------------------


class TestNotes:
    def test_get_note_folders(self, svc):
        with patch.object(
            svc, "_run_applescript_file", return_value="Notes|||Ideas|||"
        ):
            assert svc.get_note_folders() == ["Notes", "Ideas"]

    def test_get_notes_all(self, svc):
        raw = "Shopping|2026-07-01, Ideas|2026-07-02"
        with patch.object(svc, "_run_applescript_file", return_value=raw):
            notes = svc.get_notes()
        assert notes[0] == {"title": "Shopping", "created": "2026-07-01"}
        assert notes[1]["title"] == "Ideas"

    def test_get_notes_folder_in_script(self, svc):
        with patch.object(svc, "_run_applescript_file", return_value="") as m:
            svc.get_notes(folder_name="Work", limit=3)
        assert 'folder "Work"' in m.call_args.args[0]

    def test_get_notes_error_returns_empty(self, svc):
        with patch.object(
            svc, "_run_applescript_file", side_effect=OSAScriptError("x")
        ):
            assert svc.get_notes() == []

    def test_create_note_escapes_body(self, svc):
        note = Note(title="T", body='say "hi"\nbye')
        with patch.object(svc, "_run_applescript_file", return_value="") as m:
            assert svc.create_note(note) is True
        script = m.call_args.args[0]
        assert '\\"hi\\"' in script
        assert "\\n" in script

    def test_create_note_failure(self, svc):
        with patch.object(
            svc, "_run_applescript_file", side_effect=OSAScriptError("x")
        ):
            assert svc.create_note(Note(title="T", body="b")) is False


# ---------------------------------------------------------------------------
# Safari
# ---------------------------------------------------------------------------


class TestSafari:
    def test_get_safari_tabs(self, svc):
        raw = "Anthropic|https://a.com, Docs|https://b.com"
        with patch.object(svc, "_run_applescript_file", return_value=raw):
            tabs = svc.get_safari_tabs()
        assert tabs[0] == {"title": "Anthropic", "url": "https://a.com"}
        assert tabs[1]["url"] == "https://b.com"

    def test_get_safari_tabs_error(self, svc):
        with patch.object(
            svc, "_run_applescript_file", side_effect=OSAScriptError("x")
        ):
            assert svc.get_safari_tabs() == []

    def test_get_current_safari_url(self, svc):
        with patch.object(
            svc, "_run_applescript_file", return_value="https://x.com"
        ):
            assert svc.get_current_safari_url() == "https://x.com"

    def test_get_current_safari_url_error_none(self, svc):
        with patch.object(
            svc, "_run_applescript_file", side_effect=OSAScriptError("x")
        ):
            assert svc.get_current_safari_url() is None

    def test_open_url_new_tab(self, svc):
        with patch.object(svc, "_run_applescript_file", return_value="") as m:
            assert svc.open_url_in_safari("https://x.com", new_tab=True) is True
        assert "make new tab" in m.call_args.args[0]

    def test_open_url_same_tab(self, svc):
        with patch.object(svc, "_run_applescript_file", return_value="") as m:
            assert svc.open_url_in_safari("https://x.com", new_tab=False) is True
        assert "set URL of current tab" in m.call_args.args[0]

    def test_open_url_failure(self, svc):
        with patch.object(
            svc, "_run_applescript_file", side_effect=OSAScriptError("x")
        ):
            assert svc.open_url_in_safari("https://x.com") is False


# ---------------------------------------------------------------------------
# Contactos
# ---------------------------------------------------------------------------


class TestContacts:
    def test_search_contacts(self, svc):
        raw = "John Doe|john@x.com|555"
        with patch.object(svc, "_run_applescript_file", return_value=raw):
            contacts = svc.search_contacts("John")
        assert contacts == [
            {"name": "John Doe", "email": "john@x.com", "phone": "555"}
        ]

    def test_search_contacts_missing_values(self, svc):
        raw = "Jane|missing value|missing value"
        with patch.object(svc, "_run_applescript_file", return_value=raw):
            contacts = svc.search_contacts("Jane")
        assert contacts[0]["email"] is None
        assert contacts[0]["phone"] is None

    def test_search_contacts_error(self, svc):
        with patch.object(
            svc, "_run_applescript_file", side_effect=OSAScriptError("x")
        ):
            assert svc.search_contacts("x") == []


# ---------------------------------------------------------------------------
# Finder
# ---------------------------------------------------------------------------


class TestFinder:
    def test_get_selected_files(self, svc):
        with patch.object(
            svc, "_run_applescript_file", return_value="/a/b.txt, /c/d.png"
        ):
            assert svc.get_selected_files() == ["/a/b.txt", "/c/d.png"]

    def test_get_selected_files_empty(self, svc):
        with patch.object(svc, "_run_applescript_file", return_value=""):
            assert svc.get_selected_files() == []

    def test_get_selected_files_error(self, svc):
        with patch.object(
            svc, "_run_applescript_file", side_effect=OSAScriptError("x")
        ):
            assert svc.get_selected_files() == []

    def test_reveal_in_finder_success(self, svc):
        with patch.object(svc, "_run_applescript_file", return_value=""):
            assert svc.reveal_in_finder("/tmp/x") is True

    def test_reveal_in_finder_failure(self, svc):
        with patch.object(
            svc, "_run_applescript_file", side_effect=OSAScriptError("x")
        ):
            assert svc.reveal_in_finder("/tmp/x") is False


# ---------------------------------------------------------------------------
# Clipboard
# ---------------------------------------------------------------------------


class TestClipboard:
    def test_get_clipboard(self, svc):
        with patch.object(svc, "_run_applescript", return_value="copied"):
            assert svc.get_clipboard() == "copied"

    def test_get_clipboard_error_returns_empty(self, svc):
        with patch.object(svc, "_run_applescript", side_effect=OSAScriptError("x")):
            assert svc.get_clipboard() == ""

    def test_set_clipboard_success(self, svc):
        with patch.object(svc, "_run_applescript", return_value="") as m:
            assert svc.set_clipboard("hello") is True
        assert "hello" in m.call_args.args[0]

    def test_set_clipboard_failure(self, svc):
        with patch.object(svc, "_run_applescript", side_effect=OSAScriptError("x")):
            assert svc.set_clipboard("hello") is False


# ---------------------------------------------------------------------------
# Music
# ---------------------------------------------------------------------------


class TestMusic:
    def test_get_current_track_playing(self, svc):
        with patch.object(
            svc, "_run_applescript_file", return_value="Song|Artist|Album"
        ):
            track = svc.get_current_track()
        assert track == {"track": "Song", "artist": "Artist", "album": "Album"}

    def test_get_current_track_not_playing_none(self, svc):
        with patch.object(svc, "_run_applescript_file", return_value=""):
            assert svc.get_current_track() is None

    def test_get_current_track_error_none(self, svc):
        with patch.object(
            svc, "_run_applescript_file", side_effect=OSAScriptError("x")
        ):
            assert svc.get_current_track() is None

    def test_music_play_pause_success(self, svc):
        with patch.object(svc, "_run_applescript", return_value=""):
            assert svc.music_play_pause() is True

    def test_music_play_pause_failure(self, svc):
        with patch.object(svc, "_run_applescript", side_effect=OSAScriptError("x")):
            assert svc.music_play_pause() is False
