"""
Tests for TunnelService (app.services.tunnel).

Generated by Codex CLI (gpt-5.4) -- comprehensive pytest test suite.

Mocks pyngrok.ngrok completely via sys.modules patching.
Tests: start(), stop(), get_info(), is_connected property, public_url property,
       error handling, singleton get_tunnel_service.
Uses pytest-asyncio with async tests and unittest.mock.patch.
"""

import sys
from unittest.mock import MagicMock, patch

import pytest

import app.services.tunnel as tunnel_module
from app.services.tunnel import TunnelService, get_tunnel_service

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_tunnel_obj(public_url="https://abc123.ngrok.io"):
    """Create a mock ngrok tunnel object."""
    t = MagicMock()
    t.public_url = public_url
    t.proto = "https"
    t.config = {"addr": "8888"}
    return t


def _mock_pyngrok(ngrok_mock=None, conf_mock=None):
    """Create mock pyngrok modules for sys.modules patching."""
    mock_ngrok = ngrok_mock or MagicMock()
    mock_conf = conf_mock or MagicMock()
    pyngrok_mock = MagicMock()
    pyngrok_mock.ngrok = mock_ngrok
    pyngrok_mock.conf = mock_conf
    return {
        "pyngrok": pyngrok_mock,
        "pyngrok.ngrok": mock_ngrok,
        "pyngrok.conf": mock_conf,
    }, mock_ngrok, mock_conf


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture
def service():
    """Fresh TunnelService instance."""
    return TunnelService()


@pytest.fixture(autouse=True)
def reset_singleton():
    """Reset the module-level singleton between tests."""
    tunnel_module._tunnel_service = None
    yield
    tunnel_module._tunnel_service = None


# ---------------------------------------------------------------------------
# TestTunnelService: start()
# ---------------------------------------------------------------------------

class TestTunnelServiceStart:

    @pytest.mark.asyncio
    async def test_start_success_returns_url(self, service):
        """start() connects via ngrok and returns the public URL."""
        mock_tunnel = _make_tunnel_obj("https://test123.ngrok.io")
        modules, mock_ngrok, mock_conf = _mock_pyngrok()
        mock_ngrok.connect.return_value = mock_tunnel

        with patch.dict(sys.modules, modules):
            with patch("app.services.tunnel.settings") as s:
                s.gateway_port = 8888
                s.ngrok_authtoken = "test-token"
                s.ngrok_domain = None
                url = await service.start()

        assert url == "https://test123.ngrok.io"
        assert service.is_connected is True
        assert service.public_url == "https://test123.ngrok.io"
        assert service._started_at is not None

    @pytest.mark.asyncio
    async def test_start_sets_authtoken_when_present(self, service):
        """When ngrok_authtoken is set, it configures the auth token."""
        mock_tunnel = _make_tunnel_obj()
        modules, mock_ngrok, mock_conf = _mock_pyngrok()
        mock_ngrok.connect.return_value = mock_tunnel

        with patch.dict(sys.modules, modules):
            with patch("app.services.tunnel.settings") as s:
                s.gateway_port = 8888
                s.ngrok_authtoken = "my-auth-token"
                s.ngrok_domain = None
                await service.start()

        mock_conf.get_default.return_value.auth_token = "my-auth-token"

    @pytest.mark.asyncio
    async def test_start_with_custom_port(self, service):
        """start(port=9999) uses the provided port."""
        mock_tunnel = _make_tunnel_obj("https://custom.ngrok.io")
        modules, mock_ngrok, _ = _mock_pyngrok()
        mock_ngrok.connect.return_value = mock_tunnel

        with patch.dict(sys.modules, modules):
            with patch("app.services.tunnel.settings") as s:
                s.ngrok_authtoken = ""
                s.ngrok_domain = None
                url = await service.start(port=9999)

        assert url == "https://custom.ngrok.io"
        call_kwargs = mock_ngrok.connect.call_args[1]
        assert call_kwargs["addr"] == 9999

    @pytest.mark.asyncio
    async def test_start_uses_settings_port_when_none(self, service):
        """start() uses settings.gateway_port when port is not specified."""
        mock_tunnel = _make_tunnel_obj()
        modules, mock_ngrok, _ = _mock_pyngrok()
        mock_ngrok.connect.return_value = mock_tunnel

        with patch.dict(sys.modules, modules):
            with patch("app.services.tunnel.settings") as s:
                s.gateway_port = 7777
                s.ngrok_authtoken = ""
                s.ngrok_domain = None
                await service.start()

        call_kwargs = mock_ngrok.connect.call_args[1]
        assert call_kwargs["addr"] == 7777

    @pytest.mark.asyncio
    async def test_start_with_custom_domain(self, service):
        """When ngrok_domain is set, hostname is passed to ngrok.connect."""
        mock_tunnel = _make_tunnel_obj("https://my.domain.com")
        modules, mock_ngrok, _ = _mock_pyngrok()
        mock_ngrok.connect.return_value = mock_tunnel

        with patch.dict(sys.modules, modules):
            with patch("app.services.tunnel.settings") as s:
                s.gateway_port = 8888
                s.ngrok_authtoken = "token"
                s.ngrok_domain = "my.domain.com"
                url = await service.start()

        assert url == "https://my.domain.com"
        call_kwargs = mock_ngrok.connect.call_args[1]
        assert call_kwargs["hostname"] == "my.domain.com"

    @pytest.mark.asyncio
    async def test_start_without_domain_omits_hostname(self, service):
        """When ngrok_domain is None, hostname is not passed."""
        mock_tunnel = _make_tunnel_obj()
        modules, mock_ngrok, _ = _mock_pyngrok()
        mock_ngrok.connect.return_value = mock_tunnel

        with patch.dict(sys.modules, modules):
            with patch("app.services.tunnel.settings") as s:
                s.gateway_port = 8888
                s.ngrok_authtoken = ""
                s.ngrok_domain = None
                await service.start()

        call_kwargs = mock_ngrok.connect.call_args[1]
        assert "hostname" not in call_kwargs

    @pytest.mark.asyncio
    async def test_start_bind_tls_always_true(self, service):
        """ngrok.connect always receives bind_tls=True."""
        mock_tunnel = _make_tunnel_obj()
        modules, mock_ngrok, _ = _mock_pyngrok()
        mock_ngrok.connect.return_value = mock_tunnel

        with patch.dict(sys.modules, modules):
            with patch("app.services.tunnel.settings") as s:
                s.gateway_port = 8888
                s.ngrok_authtoken = ""
                s.ngrok_domain = None
                await service.start()

        call_kwargs = mock_ngrok.connect.call_args[1]
        assert call_kwargs["bind_tls"] is True

    @pytest.mark.asyncio
    async def test_start_already_connected_returns_existing_url(self, service):
        """If already connected, start() returns existing URL without reconnecting."""
        service._connected = True
        service._public_url = "https://existing.ngrok.io"

        url = await service.start()
        assert url == "https://existing.ngrok.io"

    @pytest.mark.asyncio
    async def test_start_import_error_returns_none(self, service):
        """When pyngrok is not installed, start() returns None."""
        import builtins
        original_import = builtins.__import__

        def mock_import(name, *args, **kwargs):
            if name == "pyngrok":
                raise ImportError("No module named 'pyngrok'")
            return original_import(name, *args, **kwargs)

        with patch("builtins.__import__", side_effect=mock_import):
            with patch("app.services.tunnel.settings") as s:
                s.gateway_port = 8888
                s.ngrok_authtoken = ""
                s.ngrok_domain = None
                url = await service.start()

        assert url is None
        assert service.is_connected is False

    @pytest.mark.asyncio
    async def test_start_connection_failure_returns_none(self, service):
        """When ngrok.connect raises, start() returns None."""
        modules, mock_ngrok, _ = _mock_pyngrok()
        mock_ngrok.connect.side_effect = RuntimeError("Connection refused")

        with patch.dict(sys.modules, modules):
            with patch("app.services.tunnel.settings") as s:
                s.gateway_port = 8888
                s.ngrok_authtoken = ""
                s.ngrok_domain = None
                url = await service.start()

        assert url is None
        assert service.is_connected is False

    @pytest.mark.asyncio
    async def test_start_generic_exception_returns_none(self, service):
        """Any exception during start() is caught and None returned."""
        modules, mock_ngrok, _ = _mock_pyngrok()
        mock_ngrok.connect.side_effect = Exception("unexpected error")

        with patch.dict(sys.modules, modules):
            with patch("app.services.tunnel.settings") as s:
                s.gateway_port = 8888
                s.ngrok_authtoken = ""
                s.ngrok_domain = None
                url = await service.start()

        assert url is None
        assert service.is_connected is False


# ---------------------------------------------------------------------------
# TestTunnelService: stop()
# ---------------------------------------------------------------------------

class TestTunnelServiceStop:

    @pytest.mark.asyncio
    async def test_stop_disconnects_and_kills(self, service):
        """stop() calls ngrok.disconnect and ngrok.kill, then resets state."""
        modules, mock_ngrok, _ = _mock_pyngrok()
        service._connected = True
        service._public_url = "https://active.ngrok.io"
        service._tunnel = _make_tunnel_obj("https://active.ngrok.io")
        service._started_at = "2026-01-01T00:00:00Z"

        with patch.dict(sys.modules, modules):
            await service.stop()

        assert service.is_connected is False
        assert service.public_url is None
        assert service._tunnel is None
        assert service._started_at is None
        mock_ngrok.disconnect.assert_called_once_with("https://active.ngrok.io")
        mock_ngrok.kill.assert_called_once()

    @pytest.mark.asyncio
    async def test_stop_when_not_connected_is_noop(self, service):
        """stop() does nothing when not connected."""
        assert service.is_connected is False
        await service.stop()
        assert service.is_connected is False

    @pytest.mark.asyncio
    async def test_stop_exception_handled_gracefully(self, service):
        """stop() handles exceptions without raising."""
        modules, mock_ngrok, _ = _mock_pyngrok()
        mock_ngrok.disconnect.side_effect = RuntimeError("crash")

        service._connected = True
        service._public_url = "https://x.ngrok.io"
        service._tunnel = _make_tunnel_obj("https://x.ngrok.io")

        with patch.dict(sys.modules, modules):
            # Should not raise
            await service.stop()


# ---------------------------------------------------------------------------
# TestTunnelService: get_info()
# ---------------------------------------------------------------------------

class TestTunnelServiceGetInfo:

    def test_get_info_when_disconnected(self, service):
        info = service.get_info()
        assert info == {
            "connected": False,
            "public_url": None,
            "started_at": None,
        }

    def test_get_info_when_connected_with_tunnels(self, service):
        modules, mock_ngrok, _ = _mock_pyngrok()
        service._connected = True
        service._public_url = "https://info.ngrok.io"
        service._started_at = "2026-03-13T10:00:00Z"

        tunnel_obj = _make_tunnel_obj("https://info.ngrok.io")
        mock_ngrok.get_tunnels.return_value = [tunnel_obj]

        with patch.dict(sys.modules, modules):
            info = service.get_info()

        assert info["connected"] is True
        assert info["public_url"] == "https://info.ngrok.io"
        assert info["started_at"] == "2026-03-13T10:00:00Z"
        assert info["tunnels_count"] == 1
        assert info["proto"] == "https"

    def test_get_info_when_connected_no_tunnels(self, service):
        modules, mock_ngrok, _ = _mock_pyngrok()
        service._connected = True
        service._public_url = "https://empty.ngrok.io"
        service._started_at = "2026-03-13T10:00:00Z"

        mock_ngrok.get_tunnels.return_value = []

        with patch.dict(sys.modules, modules):
            info = service.get_info()

        assert info["connected"] is True
        assert info["tunnels_count"] == 0
        # proto and config should not be present when no tunnels
        assert "proto" not in info

    def test_get_info_connected_pyngrok_exception(self, service):
        """get_info handles pyngrok errors gracefully when connected."""
        modules, mock_ngrok, _ = _mock_pyngrok()
        service._connected = True
        service._public_url = "https://err.ngrok.io"
        service._started_at = "2026-03-13T10:00:00Z"

        mock_ngrok.get_tunnels.side_effect = RuntimeError("API error")

        with patch.dict(sys.modules, modules):
            info = service.get_info()

        # Base info still returned despite exception
        assert info["connected"] is True
        assert info["public_url"] == "https://err.ngrok.io"
        # No tunnels_count since exception was raised
        assert "tunnels_count" not in info

    def test_get_info_tunnel_config_with_addr(self, service):
        """get_info includes config.addr when tunnel has config attribute."""
        modules, mock_ngrok, _ = _mock_pyngrok()
        service._connected = True
        service._public_url = "https://cfg.ngrok.io"
        service._started_at = "2026-01-01T00:00:00Z"

        tunnel_obj = _make_tunnel_obj()
        tunnel_obj.config = {"addr": "localhost:9999"}
        mock_ngrok.get_tunnels.return_value = [tunnel_obj]

        with patch.dict(sys.modules, modules):
            info = service.get_info()

        assert info["config"]["addr"] == "localhost:9999"

    def test_get_info_tunnel_without_config_attr(self, service):
        """get_info handles tunnel objects without config attribute."""
        modules, mock_ngrok, _ = _mock_pyngrok()
        service._connected = True
        service._public_url = "https://nocfg.ngrok.io"
        service._started_at = "2026-01-01T00:00:00Z"

        tunnel_obj = MagicMock()
        tunnel_obj.public_url = "https://nocfg.ngrok.io"
        tunnel_obj.proto = "https"
        # Remove config attribute
        del tunnel_obj.config
        mock_ngrok.get_tunnels.return_value = [tunnel_obj]

        with patch.dict(sys.modules, modules):
            info = service.get_info()

        assert info["config"] == {}


# ---------------------------------------------------------------------------
# TestTunnelService: properties
# ---------------------------------------------------------------------------

class TestTunnelServiceProperties:

    def test_is_connected_default_false(self, service):
        assert service.is_connected is False

    def test_is_connected_after_set(self, service):
        service._connected = True
        assert service.is_connected is True

    def test_public_url_default_none(self, service):
        assert service.public_url is None

    def test_public_url_after_set(self, service):
        service._public_url = "https://test.ngrok.io"
        assert service.public_url == "https://test.ngrok.io"


# ---------------------------------------------------------------------------
# Singleton get_tunnel_service
# ---------------------------------------------------------------------------

class TestTunnelServiceSingleton:

    def test_creates_instance(self):
        svc = get_tunnel_service()
        assert isinstance(svc, TunnelService)

    def test_returns_same_instance(self):
        svc1 = get_tunnel_service()
        svc2 = get_tunnel_service()
        assert svc1 is svc2

    def test_after_reset_creates_new_instance(self):
        svc1 = get_tunnel_service()
        tunnel_module._tunnel_service = None
        svc2 = get_tunnel_service()
        assert svc1 is not svc2
        assert isinstance(svc2, TunnelService)


# ---------------------------------------------------------------------------
# Integration / end-to-end flow
# ---------------------------------------------------------------------------

class TestTunnelServiceIntegration:

    @pytest.mark.asyncio
    async def test_full_lifecycle_start_info_stop(self, service):
        """Full lifecycle: start -> get_info -> stop -> get_info."""
        mock_tunnel = _make_tunnel_obj("https://lifecycle.ngrok.io")
        modules, mock_ngrok, _ = _mock_pyngrok()
        mock_ngrok.connect.return_value = mock_tunnel
        mock_ngrok.get_tunnels.return_value = [mock_tunnel]

        # Start
        with patch.dict(sys.modules, modules):
            with patch("app.services.tunnel.settings") as s:
                s.gateway_port = 8888
                s.ngrok_authtoken = ""
                s.ngrok_domain = None
                url = await service.start()

        assert url == "https://lifecycle.ngrok.io"
        assert service.is_connected is True

        # Get info while connected
        with patch.dict(sys.modules, modules):
            info = service.get_info()
        assert info["connected"] is True
        assert info["tunnels_count"] == 1

        # Stop
        with patch.dict(sys.modules, modules):
            await service.stop()

        assert service.is_connected is False

        # Get info after stop
        info_after = service.get_info()
        assert info_after["connected"] is False
        assert info_after["public_url"] is None
